# Generated by Django 5.1.7 on 2025-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='default_cover_picture.png', upload_to=''),
        ),
    ]
